name: cmake-linuxclang-win
# cmake build of tesseract and training tools with clang on ubuntu.
# src/arch/simddetect.cpp:46:10: fatal error: 'asm/hwcap.h' file not found
# cmake build of tesseract and training tools on windows.
# fails, SW program / lept.
on:
  #push:
  schedule:
    - cron: 0 22 * * *

# All these jobs are currently failing 

jobs:

  clang-linux:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: ubuntu-latest, cc: clang,  cxx: clang++ }
          
    steps:
          
      - name: Install dependencies
        run: sudo apt-get install libleptonica-dev libpango1.0-dev -y

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -DCMAKE_CC_COMPILER=${{ matrix.cfg.cc }} \
                   -DCMAKE_CXX_COMPILER=${{ matrix.cfg.cxx }} \
                   -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        run: |
             cmake --build build --config Release

  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
              submodules: recursive
      - uses: egorpugin/sw-action@master
    
      - name: Configure
        run: |
             mkdir build && cd build
             cmake -DSW_BUILD=OFF -DBUILD_TRAINING_TOOLS=OFF -DCMAKE_BUILD_TYPE=Release ..
        
      - name: Build
        run: |
             cmake --build build --config Release  --target install
             