name: Release
on:
  create:
    tags:
      - anzen-v*
  
jobs:
  build-linux:
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - platform: ubuntu22-amd64
            runs-on: ubuntu-22.04
          - platform: ubuntu24-amd64
            runs-on: ubuntu-24.04
          - platform: ubuntu22-arm64
            runs-on: ubuntu-22-arm64
          - platform: ubuntu24-arm64
            runs-on: ubuntu-24-arm64

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install autoconf libleptonica-dev -y
      - name: Build
        run: |
          ./autogen.sh
          ./linux_build.sh
          ./download_tessdata.sh
      - name: Package output
        run: tar -czvf anzen-tesseract-${{ matrix.platform }}.tar.gz -C build-out .
      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: anzen-tesseract-${{ matrix.platform }}
          path: anzen-tesseract-${{ matrix.platform }}.tar.gz

  build-macos:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install autoconf automake libtool pkgconfig leptonica
      - name: Build
        run: |
          ./autogen.sh
          ./macos_build.sh
          ./download_tessdata.sh
      - name: Package output
        run: tar -czvf anzen-tesseract-macos-arm64.tar.gz -C build-out .
      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: anzen-tesseract-macos-arm64
          path: anzen-tesseract-macos-arm64.tar.gz

  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          pattern: anzen-tesseract-*
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: anzen-tesseract-*/*.tar.gz
